image: node:13.12

variables:
  HUGO_DOWNLOAD: https://github.com/gohugoio/hugo/releases/download/v0.68.3/hugo_0.68.3_Linux-64bit.tar.gz

stages:
- build

build:
  before_script:
  - apt update && apt install wget -y
  - wget -O hugo.tar.gz ${HUGO_DOWNLOAD}
  - tar -zxvf hugo.tar.gz hugo
  - cp hugo /usr/local/bin/
  script:
  - npm install
  - hugo
  artifacts:
    paths:
    - public/
    expire_in: 1 week
