image: docker:stable

variables:
  HUGO_DOWNLOAD: https://github.com/gohugoio/hugo/releases/download/v0.68.3/hugo_extended_0.68.3_Linux-64bit.tar.gz
  CONTAINER_IMAGE_NAME: roosdotclick
  REGISTRY: registry.gitlab.com
  CONTAINER_IMAGE: $REGISTRY/rooster212/roosdotclick/$CONTAINER_IMAGE_NAME:latest
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: "" # https://gitlab.com/gitlab-org/gitlab-ce/issues/64959

stages:
- build
- docker

build:
  stage: build
  image: node:13.12-slim
  before_script:
  - apt update && apt install wget git -y
  - wget -q -O hugo.tar.gz ${HUGO_DOWNLOAD}
  - tar -zxvf hugo.tar.gz hugo
  - cp hugo /usr/local/bin/
  script:
  - npm install --silent --no-fund
  - hugo --minify
  artifacts:
    paths:
    - public/
    expire_in: 1 week
  tags:
  - docker

docker-build:
  stage: docker
  services:
  - name: docker:19.03-dind
    entrypoint: ["env", "-u", "DOCKER_HOST"]
    command: ["dockerd-entrypoint.sh"]
  before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  dependencies:
  - build
  script:
  - docker build -t $CONTAINER_IMAGE .
  - docker push $CONTAINER_IMAGE
  only:
  - master
  tags:
  - docker