baseURL = "https://roos.click"
languageCode = "en-uk"
title = "roos.click"

[taxonomies]
  tag = "tags"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.main]]
    name = "Blog"
    pre = "edit"
    url = "/blog/"
    weight = 1
  [[menu.main]]
    name = "Photography"
    pre = "camera"
    url = "/photography/"
    weight = 2

[params]
  dateFormat = "Jan 2, 2006"
  homeText1 = "Hi, I'm Jamie, a Software Developer based in Manchester. I've got a wide range of experience across varied domains and using a multitude of different technologies."
  homeText2 = "Currently I am working at [cinch](https://cinch.co.uk) in Manchester (well, remotely!) with a focus on Automation, Observability and all things AWS."