baseURL = "https://roos.click"
languageCode = "en-uk"
title = "Roos.click"

[taxonomies]
  tag = "tags"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    pre = "edit"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Photography"
    pre = "camera"
    url = "/photography/"
    weight = 3

[params]
  dateFormat = "Jan 2, 2006"
  homeText = "Checkout the Blog and Photography sections above, or see the source code [here](https://gitlab.com/Rooster212/roosdotclick). There's more to come."