baseURL = "https://example.com"
languageCode = "en-us"
title = "Hugo Blog"

[taxonomies]
  tag = "tags"
  
[permalinks]
  blog = "/:filename/"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    pre = "edit"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Photography"
    pre = "camera"
    url = "/photography/"
    weight = 3

[params]
  dateFormat = "Jan 2, 2006"
  homeText = "You just made a Hugo blog from scratch."