baseurl      = "https://roos.click"
title        = "roos.click"
languageCode = "en-uk"
theme        = "hello-friend-ng"
paginate     = 20

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home

  homeSubtitle = "Head of Software Development at ClearCycle."
  homeSubtitle2 = "I love working with AWS, CDK, Serverless Framework, and programming languages from Typescript to Golang. I'm passionate about self-hosting, sharing knowledge and improving developer velocity wherever I can."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = true

  # Enable sharing buttons, if you like
  enableSharingButtons = false

  # Metadata mostly used in document's head
  description = "roos.click site and blog"
  keywords = "homepage, blog"
  images = [""]

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/Rooster212"
  [[params.social]]
    name = "github"
    url = "https://github.com/Rooster212"
  [[params.social]]
    name = "gitlab"
    url = "https://gitlab.com/Rooster212"
  [[params.social]]
    name = "dev"
    url = "https://dev.to/rooster212"
  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/rooster212/"
  [[params.social]]
    name = "stackoverflow"
    url = "https://stackoverflow.com/users/1505511/rooster212?tab=profile"
  [[params.social]]
    name = "email"
    url = "mailto:jamie@roos.click"

[taxonomies]
  category = "blog"
  tag      = "tags"
  series   = "series"

[languages]
  [languages.en]
    title = "roos.click"
    subtitle = ""
    keywords = ""
    copyright = 'Jamie Roos'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "roos.click"
      logoHomeLink = "/"

[menu]
  [[menu.main]]
    name       = "Blog"
    url        = "/posts"
    weight     = 1
  [[menu.main]]
    name       = "Contact"
    url        = "/contact"
    weight     = 100

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
