baseURL = "https://roos.click"
languageCode = "en-uk"
title = "Roos.click"

[taxonomies]
  tag = "tags"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    pre = "edit"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Photography"
    pre = "camera"
    url = "/photography/"
    weight = 3

[params]
  dateFormat = "Jan 2, 2006"
  homeText = "I'm Jamie Roos, I'm a developer currently based in Manchester. I've got experience working for many companies, and I enjoy development outside of work time as well. This website is [open source here](https://gitlab.com/Rooster212/roosdotclick)."